<?xml version="1.0" ?>
<robot name="$(arg robotName)" xmlns:xacro="http://ros.org/wiki/xacro">


    <!-- #### constants #### -->
    <xacro:property name="deg_to_rad" value="0.017453"/>
    <xacro:property name="PI" value="3.14"/>

    <!-- #### body property #### -->
    <xacro:property name="body_length" value="1.2"/>
    <xacro:property name="body_width" value=".45"/>
    <xacro:property name="body_height" value=".45"/>

    <!-- ####  leg property #### -->
    <xacro:property name="leg_radius" value="0.025"/>
    <xacro:property name="leg_length" value="0.32"/>
    <xacro:property name="leg_mass" value="2.5"/>

    <!-- ####  rod property #### -->
    <xacro:property name="rod_radius" value="0.031"/>
    <xacro:property name="rod_length" value="0.3596"/>
    <xacro:property name="rod_mass" value="1.0"/>

    <!-- ####  Aruco property #### -->
    <xacro:property name="aruco_width" value="0.25"/>
    <xacro:property name="aruco_length" value="0.25"/>
    <xacro:property name="aruco_height" value="0.01"/>
    <xacro:property name="aruco_z" value="1."/>
    <xacro:property name="aruco_mass" value="0.1"/>
    <xacro:property name="edge_width" value="0.1"/>


    <!-- ######################################### -->
    <!-- begin           MACRO               begin -->
    <!-- ######################################### -->

    <xacro:macro name="cylinder_inertia" params ="m r h"> 
        <inertial> 
            <mass value="${m}"/> 
            <inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0.0" ixz="0.0" 
                     iyy="${m*(3*r*r+h*h)/12}" iyz= "0.0" 
                     izz="${m*r*r/2}"/> 
         </inertial> 
     </xacro:macro>

    <xacro:macro name="cuboid_inertia" params ="m w l h"> 
        <inertial> 
            <mass value="${m}"/> 
            <inertia ixx="${m*(w*w+h*h)/12}" ixy="0.0" ixz="0.0" 
                     iyy="${m*(l*l+h*h)/12}" iyz= "0.0" 
                     izz="${m*(w*w+l*l)/12}"/> 
         </inertial> 
     </xacro:macro>

    <!-- #####  leg macro  ##### -->
    <xacro:macro name="leg" params= "prefix suffix X1 Y1">
           
      <joint name="${prefix}_${suffix}_leg_joint" type="fixed">
        <parent link= "body"/>
        <child link= "${prefix}_${suffix}_leg"/>
        <origin xyz= "${(body_length/2)*X1} ${(body_width/2)*Y1}  ${leg_length/2}" rpy="0 0 0"/>
        <dynamics damping="0.0" friction="0.0"/>  
      </joint>

      <link name= "${prefix}_${suffix}_leg">
        <!-- usefule to visualize when debugging
        <visual>
          <origin rpy= "0 0 0" xyz= "0 0 0"/>
          <geometry>   
            <cylinder length="${leg_length}" radius= "${leg_radius}"/>
          </geometry>
          <material name= "light_black"/>
        </visual>
    -->
        
        <collision>
          <origin rpy= "0 0 0" xyz= "0 0 0"/>
          <geometry>
            <cylinder length="${leg_length}" radius= "${leg_radius}"/>
          </geometry>
        </collision>
        <xacro:cylinder_inertia m="${leg_mass}" r="${leg_radius}" h="${leg_length}"/>
      </link>
         
      <gazebo reference ="${prefix}_${suffix}_leg">
        <mu1 value=".005"/>
        <mu2 value=".005"/>
        <kp value="10000000.0"/>
        <kd value= "10.0"/>
        <maxVel>0.</maxVel>
        <minDepth>0.001</minDepth>
      </gazebo>
                 
    </xacro:macro>

    <xacro:macro name="ball_leg" params= "prefix suffix X1 Y1">
               
      <joint name="${prefix}_${suffix}_ball_leg_joint" type="fixed">
        <parent link= "body"/>
        <child link= "${prefix}_${suffix}_leg"/>
        <origin xyz= "${(body_length/2)*X1} ${(body_width/2)*Y1}  ${leg_radius}" rpy="0 0 0"/>
        <dynamics damping="0.0" friction="0.0"/>  
      </joint>

      <link name= "${prefix}_${suffix}_leg">
        <!-- usefule to visualize when debugging
        <visual>
          <origin rpy= "0 0 0" xyz= "0 0 0"/>
          <geometry>   
            <sphere radius= "${leg_radius}"/>
          </geometry>
          <material name= "light_black"/>
        </visual>
        -->
        <collision>
          <origin rpy= "0 0 0" xyz= "0 0 0"/>
          <geometry>
            <sphere radius= "${leg_radius}"/>
          </geometry>
        </collision>
        <xacro:cylinder_inertia m="${leg_mass}" r="${leg_radius}" h="${leg_length}"/>
      </link>
         
      <gazebo reference ="${prefix}_${suffix}_ball_leg">
        <mu1 value=".0002"/>
        <mu2 value=".0002"/>
        <kp value="10000000.0"/>
        <kd value= "10.0"/>
        <maxVel>3</maxVel>
        <minDepth>0.001</minDepth>
      </gazebo>
                     
    </xacro:macro>

    <!-- #####  Aruco macro  ##### -->
        <!-- Aruco facing four directions-->
    <xacro:macro name="aruco" params= "prefix X1 Y1 Yaw aruco_id">
      <joint name="${prefix}_joint" type="fixed">
        <parent link= "body"/>
        <child link= "${prefix}_aruco"/>
        <origin xyz= "${(body_length/2)*X1} ${(body_width/2)*Y1} ${aruco_z}" rpy="${PI/2} 0 ${Yaw*PI/2}"/>
        <dynamics damping="0.0" friction="0.0"/>  
      </joint>

      <link name= "${prefix}_aruco">
        <visual>
          <origin rpy= "0 0 0" xyz= "0 0 0"/>
          <geometry>   
              <box size="${aruco_length} ${aruco_width} ${aruco_height}"/>
          </geometry>
        </visual>
        <collision>
          <origin rpy= "0 0 0" xyz= "0 0 0"/>
          <geometry>
              <box size="${aruco_length} ${aruco_width} ${aruco_height}"/>
          </geometry>
        </collision>
        <xacro:cuboid_inertia m="${aruco_mass}" w="${aruco_width}" l="${aruco_length}" h="${aruco_height}"/>

      </link>

      <gazebo reference="${prefix}_aruco">
          <material>SOLab/aruco${aruco_id}</material>
      </gazebo>

        <!-- Back Board for white edges -->
      <joint name="${prefix}_whiteboarder_joint" type="fixed">
        <parent link= "body"/>
        <child link= "${prefix}_aruco_whiteboarder"/>
        <origin xyz= "${(body_length/2-aruco_height*1/3)*X1} ${(body_width/2-aruco_height*1/3)*Y1} ${aruco_z}" rpy="${PI/2} 0 ${Yaw*PI/2}"/>
        <dynamics damping="0.0" friction="0.0"/>  
      </joint>

      <link name= "${prefix}_aruco_whiteboarder">
        <visual>
          <origin rpy= "0 0 0" xyz= "0 0 0"/>
          <geometry>   
              <box size="${aruco_length+edge_width} ${aruco_width+edge_width} ${aruco_height}"/>
          </geometry>
        </visual>
        <collision>
          <origin rpy= "0 0 0" xyz= "0 0 0"/>
          <geometry>
              <box size="${aruco_length+edge_width} ${aruco_width+edge_width} ${aruco_height}"/>
          </geometry>
        </collision>
        <xacro:cuboid_inertia m="${aruco_mass}" w="${aruco_width+edge_width}" l="${aruco_length+edge_width}" h="${aruco_height}"/>
      </link>
      <gazebo reference="${prefix}_aruco_whiteboarder">
          <material>SOLab/WhiteGlow</material>
      </gazebo>

    </xacro:macro>


<!-- ##################################### -->
<!-- end           MACRO               end -->
<!-- ##################################### -->

  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="body" />
    <origin xyz="0 0 0.0" rpy="0 0 0"/>
  </joint>

  <!-- body-->
  <link name="body">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
          <mesh filename="package://amr_description/meshes/shelft/only_shelft_XL.stl" scale="0.01 0.01 0.01"/>
      </geometry>
    </visual>

    <collision>
      <origin rpy="0 0 0" xyz="0 0 0.1"/>
      <geometry>
          <mesh filename="package://amr_description/meshes/shelft/only_shelft_XL.stl" scale="0.01 0.01 0.01"/>
      </geometry>
<!--
       <origin rpy="0 0 0" xyz="0 0 ${leg_length + body_height/2}"/>
       <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
       </geometry>
-->
     </collision>
     <inertial>
         <mass value="1.0"/>
              <inertia ixx="1.3542" ixy="0.0"
                       iyy="1.3542" iyz="0.0"
                       izz="1.3542" ixz="0.0"/>
    </inertial>
   </link>

  <gazebo reference="body">
      <material>Gazebo/CeilingTiled</material>
  </gazebo>

<!-- #### 4 legs #### -->
  <xacro:ball_leg prefix="right" suffix="front" X1="1" Y1="-1"/>
  <xacro:ball_leg prefix="right" suffix="back" X1="-1" Y1="-1"/>
  <xacro:ball_leg prefix="left" suffix="front" X1="1" Y1="1"/>
  <xacro:ball_leg prefix="left" suffix="back" X1="-1" Y1="1"/>


<!-- #### B bottom 1 #### -->
  <joint name="B_bot_1_joint" type="fixed">
    <parent link="body"/>
    <child link="B_bot_1" />
    <origin xyz="${body_length/2 - 0.22} 0 ${leg_length-0.025} " rpy="0 0 0"/>
  </joint>

  <link name="B_bot_1">
    <visual>
      <origin xyz="0.0 0 0.0" rpy="${PI} 0 ${PI/2}"/>
      <geometry>
        <cylinder length="${rod_length}" radius= "${rod_radius}"/>
      </geometry>
      <material name="light_black"/>
    </visual>

    <collision>
      <max_contacts>1</max_contacts>
      <origin xyz="0.0 0 0.0" rpy="${PI} 0 ${PI/2}"/>
      <geometry>
        <cylinder length="${rod_length}" radius= "${rod_radius}"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia m="${rod_mass}" r="${rod_radius}" h="${rod_length}"/>
  </link>



<!-- #### B bottom 2 #### -->
  <joint name="B_bot_2_joint" type="fixed">
    <parent link="body"/>
    <child link="B_bot_2" />
    <origin xyz="${-body_length/2 + 0.22} 0 ${leg_length -0.025} " rpy="0 0 0"/>
  </joint>

  <link name="B_bot_2">
    <visual>
      <origin xyz="0.0 0 0.0" rpy="${PI} 0 ${PI/2}"/>
      <geometry>
        <cylinder length="${rod_length}" radius= "${rod_radius}"/>
      </geometry>
      <material name="light_black"/>
    </visual>

    <collision>
      <max_contacts>1</max_contacts>
      <origin xyz="0.0 0 0.0" rpy="${PI} 0 ${PI/2}"/>
      <geometry>
        <cylinder length="${rod_length}" radius= "${rod_radius}"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia m="${rod_mass}" r="${rod_radius}" h="${rod_length}"/>
  </link>


  <!-- Aruco spawn -->
  <xacro:aruco prefix="east" X1="0" Y1="-1" Yaw="0" aruco_id="203"/>
  <xacro:aruco prefix="west" X1="0" Y1="1" Yaw="0"  aruco_id="201"/>
  <xacro:aruco prefix="north" X1="1" Y1="0" Yaw="1" aruco_id="200"/>
  <xacro:aruco prefix="south" X1="-1" Y1="0" Yaw="1" aruco_id="202"/>

  <gazebo reference="B_bot_1">
      <mu1>10</mu1>
      <mu2>10</mu2>
      <kp>1000000</kp> 
      <kd>10</kd>
      <maxVel>0.</maxVel>
      <minDepth>0.001</minDepth>
      <material>Gazebo/Wood</material>
  </gazebo>

  <gazebo reference="B_bot_2">
      <mu1>10</mu1>
      <mu2>10</mu2>
      <kp>1000000</kp> 
      <kd>10</kd>
      <maxVel>0.</maxVel>
      <minDepth>0.001</minDepth>
      <material>Gazebo/Wood</material>
  </gazebo>

<!-- ############################################### -->
<!-- begin         SOLAMR  MACRO               begin -->
<!-- ############################################### -->


  <xacro:include filename="$(find amr_description)/urdf/common_properties.xacro"/>
  <xacro:include filename="$(find amr_description)/urdf/2in1.gazebo.xacro"/>

  <xacro:property name="r200_cam_rgb_px" value="0.005"/>
  <xacro:property name="r200_cam_rgb_py" value="0.018"/>
  <xacro:property name="r200_cam_rgb_pz" value="0.013"/>
  <xacro:property name="r200_cam_depth_offset" value="0.01"/>

    <!-- #### constants #### -->
    <xacro:property name="deg_to_rad" value="0.017453"/>
    <xacro:property name="PI" value="3.14"/>

    <xacro:macro name="cylinder_inertia" params ="m r h"> 
        <inertial> 
            <mass value="${m}"/> 
            <inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0.0" ixz="0.0" 
                     iyy="${m*(3*r*r+h*h)/12}" iyz= "0.0" 
                     izz="${m*r*r/2}"/> 
         </inertial> 
     </xacro:macro>

    <!-- #### chassis property #### -->
    <xacro:property name="chassis_length" value=".3"/>
    <xacro:property name="chassis_width" value=".3"/>
    <xacro:property name="chassis_height" value="0.05"/>

    <!-- ####  caster property #### -->
    <xacro:property name="caster_radius" value="0.025"/>
    <xacro:property name="caster_length" value="0.015"/>
    <xacro:property name="caster_mass" value=".2"/>


<!-- ########################################### -->
<!-- end         SOLAMR  MACRO               end -->
<!-- ########################################### -->

<!-- ######################################################## -->
<!-- ####SOLAMR1 SOLAMR1 SOLAMR1 SOLAMR1 SOLAMR1 SOLAMR1 #### -->
<!-- ######################################################## -->
    <!-- #####  caster macro  ##### -->

    <xacro:macro name="caster_1" params= "prefix suffix X1 X2 Y1 Y2">
                     
      <joint name="${prefix}_${suffix}_caster_joint_1" type="fixed">
        <parent link= "chassis_1"/>
        <child link= "${prefix}_${suffix}_caster_1"/>
        <origin xyz= "${(chassis_length/2)*X1 + (chassis_length/2-.05)*X2} ${(chassis_width/2-0.02)*Y1 + (chassis_width/2)*Y2} 0 " rpy="0 0 0"/>
        <dynamics damping="0.0" friction="0.0"/>  
      </joint>
               
      <link name= "${prefix}_${suffix}_caster_1">
        <visual>
          <origin rpy= "${PI/2} 0 0" xyz= "0 0 0"/>
          <geometry>
              <mesh filename="package://amr_description/meshes/solamr/caster.stl" scale="0.0002 0.0002 0.0002"/>
          </geometry>
          <material name= "grey"/>
        </visual>
        <collision>
          <origin rpy= "${PI/2} 0 0" xyz= "0 0 ${caster_radius + 0.0011}"/>
          <geometry>
            <cylinder length="${caster_length}" radius= "${caster_radius}"/>
          </geometry>
        </collision>
        <xacro:cylinder_inertia m="${caster_mass}" r="${caster_radius}" h="${caster_length}"/>
      </link>
             
         
      <gazebo reference ="${prefix}_${suffix}_caster_1">
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
        <kp value="10000000.0"/>
        <kd value= "1.0"/>
        <material>Gazebo/WhiteGlow</material>
      </gazebo>
    </xacro:macro>

<!-- #####   BEGIN  ##### -->
<!-- #####  A1 PART ##### -->
<!-- #####   BEGIN  ##### -->

  <joint name="base_joint_1" type="continuous">
    <parent link="B_bot_1"/>
    <child link="chassis_1" />
    <origin xyz="0 0 ${-leg_length+0.025-0.01}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>
<!--
  <transmission name="solamr_1_tran" type="SimpleTransmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="base_joint_1">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="solamr_1_tran_motor">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
-->
  <link name="chassis_1">
    <visual>
      <origin xyz="0.0 0 0.075" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="white"/>
    </visual>

    <collision>
      <origin xyz="0.0 0 0.075" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="50"/>
      <inertia ixx="1.15625e-01" ixy="0" ixz="0"
               iyy="1.15625e-01" iyz="0"
               izz="2.25e-01" />
    </inertial>
  </link>

  <joint name="wheel_left_joint_1" type="continuous">
    <parent link="chassis_1"/>
    <child link="wheel_left_link_1"/>
    <origin xyz="0.0 ${chassis_width/2-0.05} ${0.033*1.5}" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_left_link_1">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
          <mesh filename="package://amr_description/meshes/solamr/left_tire.stl" scale="0.0015 0.0015 0.0015"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
          <cylinder length="0.018" radius="${0.033*1.5}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-02" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
      </inertial>
  </link>

  <joint name="wheel_right_joint_1" type="continuous">
    <parent link="chassis_1"/>
    <child link="wheel_right_link_1"/>
    <origin xyz="0.0 -${chassis_width/2-0.05} ${0.033*1.5}" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_right_link_1">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
          <mesh filename="package://amr_description/meshes/solamr/right_tire.stl" scale="0.0015 0.0015 0.0015"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
          <cylinder length="0.018" radius="${0.033*1.5}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-02" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
      </inertial>
  </link>

<!-- #### 4 casters #### -->
  <xacro:caster_1 prefix="right" suffix="front" X1="0" X2="1" Y1="-1" Y2="0" />
  <xacro:caster_1 prefix="right" suffix="back" X1="-1" X2="0" Y1="-1" Y2="0"/>
  <xacro:caster_1 prefix="left" suffix="front" X1="0" X2="1" Y1="0" Y2="1"/>
  <xacro:caster_1 prefix="left" suffix="back" X1="-1" X2="0" Y1="0" Y2="1"/>

<!-- #### Sensors : Lidar #### -->

  <joint name="scan_joint_11" type="fixed">
    <parent link="chassis_1"/>
    <child link="scan_front_1"/>
    <origin xyz="${chassis_length/2-0.03} ${chassis_width/2-0.03} 0.16" rpy="0 0 -${PI/2}"/>
  </joint>

  <link name="scan_front_1">
    <visual>
      <origin xyz="0 0 -.06" rpy="${PI/2} 0 0"/>
      <geometry>
        <mesh filename="package://amr_description/meshes/sensors/hokuyo_lidar.stl" scale="0.012 0.012 0.012"/>
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <origin xyz="0 0 -.03" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.08" radius="0.025"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.114" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <joint name="scan_joint_12" type="fixed">
    <parent link="chassis_1"/>
    <child link="scan_rear_1"/>
    <origin xyz="-${chassis_length/2-0.03} -${chassis_width/2-0.03} 0.16" rpy="0 0 ${PI/2}"/>
  </joint>

  <link name="scan_rear_1">
    <visual>
      <origin xyz="0 0 -.06" rpy="${PI/2} 0 0"/>
      <geometry>
        <mesh filename="package://amr_description/meshes/sensors/hokuyo_lidar.stl" scale="0.012 0.012 0.012"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <collision>
      <origin xyz="0 0 -0.03" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.08" radius="0.025"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.114" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

<!-- #####    END   ##### -->
<!-- #####  A1 PART ##### -->
<!-- #####    END   ##### -->

<!-- #####   BEGIN  ##### -->
<!-- #####  A2 PART ##### -->
<!-- #####   BEGIN  ##### -->

  <joint name="A2_top_joint_1" type="fixed">
    <parent link="chassis_1"/>
    <child link="A2_top_1" />
    <origin xyz="0 0 0.1" rpy="0 0 0"/>
  </joint>

  <link name="A2_top_1">
    <visual>
      <origin xyz="0.0 0 0.0" rpy="0 0 0"/>
      <geometry>
          <mesh filename="package://amr_description/meshes/solamr/rod_A_top_100.stl" scale="0.0065 0.0065 0.0065"/>
      </geometry>
      <material name="white"/>
    </visual>

    <collision>
      <max_contacts>1</max_contacts>
      <origin xyz="0.0 0 0.0" rpy="0 0 0"/>
      <geometry>
          <mesh filename="package://amr_description/meshes/solamr/rod_A_top_100.stl" scale="0.0065 0.0065 0.0065"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1.5"/>
      <inertia ixx="2.15625e-02" ixy="0" ixz="0"
               iyy="2.15625e-02" iyz="0"
               izz="2.25e-02" />
    </inertial>
  </link>

<!-- #####    END   ##### -->
<!-- #####  A2 PART ##### -->
<!-- #####    END   ##### -->
<!-- Begin of camera -->

  <joint name="camera_joint_1" type="fixed">
    <origin xyz="0.15 0 0.161" rpy="0 -0.35 0"/>
    <parent link="chassis_1"/>
    <child link="camera_link_1"/>
  </joint>

  <link name="camera_link_1">
    <visual>
     <origin xyz="0 0 0" rpy="1.57 0 1.57"/>
      <geometry>
          <mesh filename="package://amr_description/meshes/sensors/r200.dae" />
      </geometry>
    </visual>
    <!--
    <collision>
      <origin xyz="0.003 0.065 0.007" rpy="0 0 0"/>
      <geometry>
        <box size="0.012 0.132 0.020"/>
      </geometry>
    </collision>
-->
  </link>

  <joint name="camera_rgb_joint_1" type="fixed">
    <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="camera_link_1"/>
    <child link="camera_rgb_frame_1"/>
  </joint>
  <link name="camera_rgb_frame_1"/>

  <joint name="camera_rgb_optical_joint_1" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_rgb_frame_1"/>
    <child link="camera_rgb_optical_frame_1"/>
  </joint>
  <link name="camera_rgb_optical_frame_1"/>

  <joint name="camera_depth_joint_1" type="fixed">
    <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py + r200_cam_depth_offset} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="camera_link_1"/>
    <child link="camera_depth_frame_1"/>
  </joint>
  <link name="camera_depth_frame_1"/>

  <joint name="camera_depth_optical_joint_1" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_depth_frame_1"/>
    <child link="camera_depth_optical_frame_1"/>
  </joint>
  <link name="camera_depth_optical_frame_1"/>

<!-- End of camera -->
<!-- ######################################################## -->
<!-- ####SOLAMR2 SOLAMR2 SOLAMR2 SOLAMR2 SOLAMR2 SOLAMR2 #### -->
<!-- ######################################################## -->
    <!-- #####  caster macro  ##### -->

    <xacro:macro name="caster_2" params= "prefix suffix X1 X2 Y1 Y2">
                     
      <joint name="${prefix}_${suffix}_caster_joint_2" type="fixed">
        <parent link= "chassis_2"/>
        <child link= "${prefix}_${suffix}_caster_2"/>
        <origin xyz= "${(chassis_length/2)*X1 + (chassis_length/2-.05)*X2} ${(chassis_width/2-0.02)*Y1 + (chassis_width/2)*Y2} 0 " rpy="0 0 0"/>
        <dynamics damping="0.0" friction="0.0"/>  
      </joint>
               
      <link name= "${prefix}_${suffix}_caster_2">
        <visual>
          <origin rpy= "${PI/2} 0 0" xyz= "0 0 0"/>
          <geometry>
              <mesh filename="package://amr_description/meshes/solamr/caster.stl" scale="0.0002 0.0002 0.0002"/>
          </geometry>
          <material name= "grey"/>
        </visual>
        <collision>
          <origin rpy= "${PI/2} 0 0" xyz= "0 0 ${caster_radius + 0.0011}"/>
          <geometry>
            <cylinder length="${caster_length}" radius= "${caster_radius}"/>
          </geometry>
        </collision>
        <xacro:cylinder_inertia m="${caster_mass}" r="${caster_radius}" h="${caster_length}"/>
      </link>
             
         
      <gazebo reference ="${prefix}_${suffix}_caster_2">
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
        <kp value="10000000.0"/>
        <kd value= "1.0"/>
        <material>Gazebo/WhiteGlow</material>
      </gazebo>
    </xacro:macro>

<!-- #####   BEGIN  ##### -->
<!-- #####  A1 PART ##### -->
<!-- #####   BEGIN  ##### -->

  <joint name="base_joint_2" type="continuous">
    <parent link="body"/>
    <child link="chassis_2" />
    <origin xyz="${-body_length/2 + 0.22} 0 -0.01" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>
<!--
  <transmission name="solamr_2_tran" type="SimpleTransmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="base_joint_2">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="solamr_2_tran_motor">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
-->
<!--
  <joint name="base_joint_2" type="fixed">
    <parent link="body"/>
    <child link="chassis_2" />
    <origin xyz="${-body_length/2 + 0.22} 0 -0.01" rpy="0 0 0"/>
  </joint>
-->
  <link name="chassis_2">
    <visual>
      <origin xyz="0.0 0 0.075" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="white"/>
    </visual>

    <collision>
      <origin xyz="0.0 0 0.075" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="50"/>
      <inertia ixx="1.15625e-01" ixy="0" ixz="0"
               iyy="1.15625e-01" iyz="0"
               izz="2.25e-01" />
    </inertial>
  </link>

  <joint name="wheel_left_joint_2" type="continuous">
    <parent link="chassis_2"/>
    <child link="wheel_left_link_2"/>
    <origin xyz="0.0 ${chassis_width/2-0.05} ${0.033*1.5}" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_left_link_2">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
          <mesh filename="package://amr_description/meshes/solamr/left_tire.stl" scale="0.0015 0.0015 0.0015"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
          <cylinder length="0.018" radius="${0.033*1.5}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-02" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
      </inertial>
  </link>

  <joint name="wheel_right_joint_2" type="continuous">
    <parent link="chassis_2"/>
    <child link="wheel_right_link_2"/>
    <origin xyz="0.0 -${chassis_width/2-0.05} ${0.033*1.5}" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_right_link_2">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
          <mesh filename="package://amr_description/meshes/solamr/right_tire.stl" scale="0.0015 0.0015 0.0015"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
          <cylinder length="0.018" radius="${0.033*1.5}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-02" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
      </inertial>
  </link>

<!-- #### 4 casters #### -->
  <xacro:caster_2 prefix="right" suffix="front" X1="0" X2="1" Y1="-1" Y2="0" />
  <xacro:caster_2 prefix="right" suffix="back" X1="-1" X2="0" Y1="-1" Y2="0"/>
  <xacro:caster_2 prefix="left" suffix="front" X1="0" X2="1" Y1="0" Y2="1"/>
  <xacro:caster_2 prefix="left" suffix="back" X1="-1" X2="0" Y1="0" Y2="1"/>

<!-- #### Sensors : Lidar #### -->

  <joint name="scan_joint_21" type="fixed">
    <parent link="chassis_2"/>
    <child link="scan_front_2"/>
    <origin xyz="${chassis_length/2-0.03} ${chassis_width/2-0.03} 0.16" rpy="0 0 -${PI/2}"/>
  </joint>

  <link name="scan_front_2">
    <visual>
      <origin xyz="0 0 -.06" rpy="${PI/2} 0 0"/>
      <geometry>
        <mesh filename="package://amr_description/meshes/sensors/hokuyo_lidar.stl" scale="0.012 0.012 0.012"/>
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <origin xyz="0 0 -.03" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.08" radius="0.025"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.114" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <joint name="scan_joint_22" type="fixed">
    <parent link="chassis_2"/>
    <child link="scan_rear_2"/>
    <origin xyz="-${chassis_length/2-0.03} -${chassis_width/2-0.03} 0.16" rpy="0 0 ${PI/2}"/>
  </joint>

  <link name="scan_rear_2">
    <visual>
      <origin xyz="0 0 -.06" rpy="${PI/2} 0 0"/>
      <geometry>
        <mesh filename="package://amr_description/meshes/sensors/hokuyo_lidar.stl" scale="0.012 0.012 0.012"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <collision>
      <origin xyz="0 0 -0.03" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.08" radius="0.025"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.114" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

<!-- #####    END   ##### -->
<!-- #####  A1 PART ##### -->
<!-- #####    END   ##### -->

<!-- #####   BEGIN  ##### -->
<!-- #####  A2 PART ##### -->
<!-- #####   BEGIN  ##### -->

  <joint name="A2_top_joint_2" type="fixed">
    <parent link="chassis_2"/>
    <child link="A2_top_2" />
    <origin xyz="0 0 0.1" rpy="0 0 0"/>
  </joint>

  <link name="A2_top_2">
    <visual>
      <origin xyz="0.0 0 0.0" rpy="0 0 0"/>
      <geometry>
          <mesh filename="package://amr_description/meshes/solamr/rod_A_top_100.stl" scale="0.0065 0.0065 0.0065"/>
      </geometry>
      <material name="white"/>
    </visual>

    <collision>
      <max_contacts>1</max_contacts>
      <origin xyz="0.0 0 0.0" rpy="0 0 0"/>
      <geometry>
          <mesh filename="package://amr_description/meshes/solamr/rod_A_top_100.stl" scale="0.0065 0.0065 0.0065"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1.5"/>
      <inertia ixx="2.15625e-02" ixy="0" ixz="0"
               iyy="2.15625e-02" iyz="0"
               izz="2.25e-02" />
    </inertial>
  </link>

<!-- #####    END   ##### -->
<!-- #####  A2 PART ##### -->
<!-- #####    END   ##### -->
<!-- Begin of camera -->

  <joint name="camera_joint_2" type="fixed">
    <origin xyz="0.15 0 0.161" rpy="0 -0.35 0"/>
    <parent link="chassis_2"/>
    <child link="camera_link_2"/>
  </joint>

  <link name="camera_link_2">
    <visual>
     <origin xyz="0 0 0" rpy="1.57 0 1.57"/>
      <geometry>
          <mesh filename="package://amr_description/meshes/sensors/r200.dae" />
      </geometry>
    </visual>
    <!--
    <collision>
      <origin xyz="0.003 0.065 0.007" rpy="0 0 0"/>
      <geometry>
        <box size="0.012 0.132 0.020"/>
      </geometry>
    </collision>
-->
  </link>

  <joint name="camera_rgb_joint_2" type="fixed">
    <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="camera_link_2"/>
    <child link="camera_rgb_frame_2"/>
  </joint>
  <link name="camera_rgb_frame_2"/>

  <joint name="camera_rgb_optical_joint_2" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_rgb_frame_2"/>
    <child link="camera_rgb_optical_frame_2"/>
  </joint>
  <link name="camera_rgb_optical_frame_2"/>

  <joint name="camera_depth_joint_2" type="fixed">
    <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py + r200_cam_depth_offset} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="camera_link_2"/>
    <child link="camera_depth_frame_2"/>
  </joint>
  <link name="camera_depth_frame_2"/>

  <joint name="camera_depth_optical_joint_2" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_depth_frame_2"/>
    <child link="camera_depth_optical_frame_2"/>
  </joint>
  <link name="camera_depth_optical_frame_2"/>

<!-- End of camera -->

</robot>
